version: '3.8'

services:
  trading-bot:
    build: .
    ports:
      - "8501:8501"
      - "8000:8000"
    volumes:
      - ./config:/app/config:ro
    environment:
      - PYTHONUNBUFFERED=1

  monitoring:
    image: prom/prometheus:v2.40.0
    ports:
      - "9090:9090"
