name: Institutional CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit -r src/ -lll

  unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: |
          pytest tests/unit/ -v

  integration-tests:
    runs-on: ubuntu-latest
    needs: [security-scan, unit-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: |
          pytest tests/integration/ -v
        env:
          TESTNET_RPC_URL: ${{ secrets.TESTNET_RPC_URL }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
